/* Escuadra · Conexión con la industria: dónde se usa cada tema en el Bajío y un planeador de visitas y charlas.
   Los ejemplos son generales y verificables (armadoras de Guanajuato según mexicoindustry.com, ago 2026; calzado de León;
   sombreros de San Francisco del Rincón). El código es público: aquí no van nombres de personas ni contactos. */
(function () {
  'use strict';
  const E = window.E, u = E.u, S = E.store, D = E.data, esc = u.esc;
  const V = E.views, A = E.actions, CH = E.changes, H = E.h;
  const card = H.card, btn = H.btn, link = H.link;
  const AUTO = 'Armadoras (GM en Silao, Mazda en Salamanca, Honda en Celaya, Toyota en Apaseo el Grande)';
  // [sector, cómo se usa]
  const IN = E.INDUSTRIA = {
    'sm1-planos': [['Autopartes del corredor Silao-León', 'Cada pieza que llega a una armadora se compra con su plano; si una cota no se cumple, el lote se rechaza.'], ['Talleres de maquinado y moldes', 'El tornero o la máquina CNC fabrican solo con el plano: nadie les explica la pieza de palabra.'], ['Mantenimiento en planta', 'Para mandar hacer una refacción (un eje, un buje) se dibuja la pieza con sus cotas.']],
    'sm1-restricciones': [['Dispositivos para líneas de ensamble', 'Los soportes y sujetadores se modelan paramétricos para cambiar medidas cuando cambia el modelo de auto.'], ['Calzado en León', 'Las hormas y los moldes de suela se diseñan en CAD y se ajustan a cada número cambiando cotas.'], ['Integradores de automatización', 'Guardas y soportes de sensores se modelan y se revisan en la computadora antes de fabricarlos.']],
    'sm2-mecanismo': [[AUTO, 'Los robots de soldadura y pintura son cadenas de eslabones unidos por pares giratorios.'], ['Calzado y confección', 'Las máquinas de coser industriales mueven la aguja con eslabones, levas y pares miles de veces por minuto.'], ['Líneas de ensamble', 'Pinzas y garras (grippers) que toman piezas: el mismo tipo de mecanismo que su proyecto.']],
    'sm2-movimientos': [['Plantas de alimentos y empaque', 'Las bandas transportadoras convierten el giro de un motor en avance lineal de las cajas.'], ['Estampado de autopartes', 'En una prensa mecánica, el giro del volante se vuelve el sube y baja del troquel.'], ['Autos que se arman en la región', 'Limpiaparabrisas (oscilante) y elevavidrios (giro a lineal) son mecanismos de esta clase.']],
    'sm2-gdl': [['Robots industriales', 'Un robot de 6 ejes tiene 6 grados de libertad: por eso lleva 6 motores.'], ['Máquinas CNC y de corte láser', 'Una mesa X-Y tiene 2 grados de libertad: un motor para cada dirección.'], ['Sujetadores de soldadura', 'Un sujetador de palanca tiene 1 grado de libertad: un solo cilindro lo abre y lo cierra.']],
    'sm2-4barras': [['Dispositivos de soldadura en autopartes', 'Los sujetadores de palanca (toggle clamps) son cuatro barras que se traban en el punto muerto para no soltar la pieza.'], ['Autos', 'Las bisagras de muchos cofres y el limpiaparabrisas usan cuatro barras.'], ['Maquinaria de empaque', 'Brazos que empujan o voltean cajas con un solo motor que gira.']],
    'sm2-biela': [['Motores', 'Mazda fabrica motores en Salamanca y Volkswagen en Silao: el pistón, la biela y el cigüeñal son este mecanismo.'], ['Aire comprimido de las plantas', 'Los compresores de pistón también son biela-manivela.'], ['Prensas mecánicas', 'El cigüeñal y la biela bajan el troquel con mucha fuerza en el estampado.']],
    'sm2-levas': [['Motores (Salamanca, Silao)', 'El árbol de levas abre y cierra las válvulas en el momento exacto.'], ['Calzado y confección', 'Las máquinas de coser sincronizan aguja, gancho y arrastre con levas.'], ['Máquinas automáticas de empaque', 'Levas que repiten el mismo movimiento miles de veces al día.']],
    'sm2-engranes': [['Transmisiones', 'Honda en Celaya tiene planta de transmisiones y GM en Silao también fabrica transmisiones: son trenes de engranes.'], ['Bandas transportadoras', 'Los motorreductores bajan la velocidad del motor y suben el par con engranes.'], ['Autos', 'El diferencial reparte el giro entre las ruedas con engranes cónicos.']],
    'sm2-poleas': [['Plantas de alimentos y paquetería', 'Las bandas transportadoras se mueven con poleas y bandas.'], ['Motores de los autos', 'La banda de accesorios mueve alternador y bomba de agua con poleas de distinto tamaño.'], ['Compresores y ventiladores industriales', 'Muchos se mueven por banda: cambiar la polea cambia la velocidad.']],
    'sm2-tornillo': [['Talleres de maquinado (CNC)', 'Los husillos de bolas convierten el giro del motor en avance preciso de la mesa.'], ['Autos', 'La dirección de piñón y cremallera mueve las llantas al girar el volante.'], ['Mantenimiento', 'Gatos mecánicos y prensas de tornillo para montar y desmontar piezas.']],
    'sm2-explosionada': [['Manuales y catálogos de refacciones', 'La vista explosionada con globos dice qué número de pieza pedir.'], ['Líneas de ensamble', 'Las instrucciones de trabajo muestran al operador cómo se arma, paso a paso.'], ['Máquinas especiales de integradores', 'Cada máquina se entrega con su plano de ensamble y lista de materiales.']],
    'sm2-materiales': [['Prototipos', 'Antes de fabricar en acero se prueba en MDF, plástico o impresión 3D, como hacen ustedes con cartón.'], ['Autopartes de plástico', 'Interiores y piezas inyectadas: se elige el material por resistencia, peso y costo.'], ['Calzado en León', 'La merma de piel, suela y plástico se separa para reciclarla o venderla.']],
    'sm2-seguridad': [['Toda planta de la región', 'Antes de dar mantenimiento se bloquea y etiqueta la energía de la máquina (bloqueo y etiquetado).'], ['Equipo de protección personal', 'Lentes, zapato de seguridad y guantes según la tarea: lo exige la NOM-017-STPS.'], ['Prensas', 'Guardas, cortinas de luz y mando con las dos manos para que nadie meta la mano.']],
    'sm3-presion': [['Neumática en planta', 'La red de aire de una planta suele trabajar alrededor de 6 bar (unos 90 psi); el manómetro de cada máquina lo muestra.'], [AUTO, 'Las llantas se inflan a la presión indicada en psi antes de salir de la línea.'], ['Hidráulica', 'Prensas y montacargas trabajan a presiones mucho mayores que la neumática.']],
    'sm3-pascal': [['Calzado en León', 'Las troqueladoras hidráulicas cortan la piel con un suaje empujado por aceite a presión.'], ['Talleres automotrices', 'Los gatos y elevadores hidráulicos levantan un auto con poca fuerza de entrada.'], ['Autos', 'Los frenos hidráulicos multiplican la fuerza del pie con la relación de áreas.']],
    'sm3-comparativa': [['Líneas de ensamble', 'Neumática para movimientos rápidos y baratos: sujetar, empujar, expulsar.'], ['Inyección y prensado', 'Hidráulica donde se necesita mucha fuerza.'], ['Robots y CNC', 'Servomotores eléctricos donde se necesita precisión y control de posición.']],
    'sm3-aire': [['Cuarto de compresores', 'Toda planta tiene compresor, secador, tanque y una red de tubería hasta cada máquina.'], ['Cada máquina', 'Una unidad de mantenimiento (filtro, regulador y lubricador) limpia y ajusta el aire de entrada.'], ['Ahorro de energía', 'Las fugas de aire son de los desperdicios más comunes; mantenimiento las busca y las repara.']],
    'sm3-cilindros': [['Calzado en León y San Francisco del Rincón', 'Prensas neumáticas que pegan la suela al corte del zapato.'], ['Dispositivos de soldadura', 'Cilindros que cierran los sujetadores y sostienen las piezas mientras se sueldan.'], ['Sombreros en San Francisco del Rincón', 'Prensas que dan forma al sombrero con calor y presión.']],
    'sm3-valvulas': [['Máquinas de ensamble', 'Varias electroválvulas 5/2 montadas en un solo bloque mueven todos los cilindros.'], ['Prensas', 'El mando con las dos manos obliga al operador a tener ambas manos lejos del troquel.'], ['Red de aire', 'Válvulas manuales para cortar y purgar el aire antes de dar mantenimiento.']],
    'sm3-iso1219': [['Mantenimiento', 'Los diagramas neumáticos de las máquinas vienen con símbolos ISO 1219.'], ['Integradores', 'Documentan cada máquina especial con su diagrama para que otro técnico la entienda.'], ['Compras', 'Para pedir una válvula se describe con vías, posiciones y accionamiento, igual que en el símbolo.']],
    'sm3-electro': [['Casi toda máquina de ensamble', 'Un PLC energiza la bobina de una electroválvula y el cilindro se mueve.'], ['Tableros eléctricos', 'Botones de arranque y paro con relevadores y contactores.'], ['Mantenimiento', 'El diagrama de escalera es el lenguaje de PLC que más se usa para encontrar fallas.']],
    'sm3-motordc': [[AUTO, 'Elevavidrios, limpiaparabrisas y asientos eléctricos se mueven con motores de CD que cambian de giro.'], ['Logística dentro de las plantas', 'Vehículos guiados que mueven material usan motores eléctricos con control de giro.'], ['Puertas automáticas', 'Abren y cierran invirtiendo el giro de un motor, como su grúa.']],
    'sm3-fallas': [['Técnico de mantenimiento', 'Su trabajo diario es ir del síntoma a la causa rápido: una línea parada cuesta mucho dinero.'], ['Mantenimiento preventivo', 'Revisar fugas, presión y desgaste antes de que algo falle.'], ['Bitácora de fallas', 'Cada falla y su solución se registra para resolverla más rápido la próxima vez.']],
    'gen-mecatronica': [['Guanajuato', 'Fue el estado con más producción de vehículos ligeros del país en 2025, y cada planta necesita técnicos de mantenimiento y automatización.'], ['Corredores industriales', 'Silao-León, Irapuato-Salamanca y Celaya-Apaseo el Grande concentran armadoras y proveedores.'], ['No solo autos', 'Calzado, alimentos, plásticos y empaque también automatizan sus procesos.']],
    'gen-mentalidad': [['Mejora continua en planta', 'Los equipos analizan cada error o defecto para que no se repita: el error es información.'], ['Mantenimiento', 'Un técnico que anota qué falló y por qué resuelve más rápido la siguiente vez.']]
  };
  const IND = E.industria = {};
  IND.de = id => IN[id] || null;
  IND.cardHTML = t => { const x = IN[t.id]; if (!x) return ''; return card('<h3>🏭 ¿Dónde se usa en el Bajío?</h3><ul class="in-list">' + x.map(r => '<li><b>' + esc(r[0]) + ':</b> ' + esc(r[1]) + '</li>').join('') + '</ul><p class="muted small">Pregunta al grupo: ¿alguien conoce a alguien que trabaje en algo así? ¿Qué hace? (Se proyecta antes de «¿Para qué me sirve?».)</p>'); };
  IND.slide = t => { const x = IN[t.id]; return x ? { k: 'list', h: '¿Dónde se usa en el Bajío?', items: x.map(r => r[0] + ': ' + r[1]) } : null; };

  /* =================== planeador de visitas, charlas y demostraciones =================== */
  const KV = g => 'visitas:' + g.id;
  const TIPOS = {
    visita: ['🏭 Visita a planta o taller', ['Permiso de dirección por escrito', 'Oficio o correo a la empresa con fecha, hora y número de alumnos', 'Autorización firmada de madre, padre o tutor de cada alumno', 'Transporte y horario de salida y regreso', 'Reglas de seguridad de la empresa (zapato cerrado, lentes, cabello recogido)', 'Lista de asistentes y teléfonos de emergencia', 'Preguntas preparadas por los alumnos', 'Agradecimiento a la empresa después', 'Reflexión en la bitácora: qué vi que se relaciona con la clase']],
    charla: ['🎤 Charla de un invitado', ['Fecha, hora y salón (con proyector si lo necesita)', 'Avisar a dirección', 'Pedirle que cuente qué hace en un día normal y qué estudió', 'Preguntas preparadas por los alumnos', 'Presentar al invitado al grupo', 'Agradecimiento (tarjeta o carta del grupo)', 'Reflexión en la bitácora']],
    demo: ['🧰 Demostración con piezas reales', ['Piezas: sensor, electroválvula, cilindro, contactor, PLC o variador', 'Qué tema de la clase muestra cada pieza', 'Reglas: se toca con cuidado y sin energía conectada', 'Pregunta-reto: ¿dónde han visto algo así?']]
  };
  const IDEAS = [['Egresado del CETAC', 'Un exalumno que ya trabaja en una planta: es el ejemplo más cercano de «yo también puedo».'], ['Técnico de mantenimiento', 'Que cuente una falla real y cómo la encontró (va perfecto con el tema de fallas).'], ['Integrador o distribuidor de automatización', 'Que muestre sensores, válvulas y un PLC de verdad, y qué hace un técnico en su empresa.'], ['Visita a un taller de la región', 'Calzado, maquinado o mantenimiento automotriz: ver neumática e hidráulica funcionando.'], ['Reto de una empresa', 'Un problema real y pequeño que los equipos intenten resolver con lo que saben.']];
  const PREG = ['¿Qué estudiaste y dónde?', '¿Cómo es un día normal en tu trabajo?', '¿Qué máquinas o sistemas usas: neumática, hidráulica, PLC, robots?', '¿Qué es lo que más falla y cómo encuentras la causa?', '¿Qué buscan en un técnico recién egresado?', '¿Qué tan importante es leer planos y usar CAD como FreeCAD?', '¿Qué tanto usas el inglés?', '¿Cómo cuidan la seguridad en tu trabajo?', '¿Qué error cometiste al empezar y qué aprendiste?', '¿Qué le recomendarías a alguien de mi edad que quiere trabajar en esto?'];
  const doc = g => S.get(KV(g)) || { items: [] };
  V.industria = () => {
    const g = D.grupoActual(); if (!g) return H.noGroup();
    const its = (doc(g).items || []).slice().sort((a, b) => String(a.fecha || '9999').localeCompare(String(b.fecha || '9999'))), hoy = u.today();
    let h = card('<h3>🏭 Conexión con la industria</h3><p class="muted small">Ver que lo de la clase es un trabajo real en la región motiva mucho. Cada tema ya trae «¿Dónde se usa en el Bajío?» (también en el proyector). Aquí planeas visitas, charlas y demostraciones con su lista de pendientes.</p>' +
      '<div class="fgrid c3"><label class="fld"><span>Tipo</span><select id="in-tipo">' + Object.keys(TIPOS).map(k => '<option value="' + k + '">' + TIPOS[k][0] + '</option>').join('') + '</select></label><label class="fld"><span>Fecha</span><input id="in-f" type="date" value=""></label><label class="fld"><span>Empresa, lugar o invitado</span><input id="in-q" placeholder="Ej. taller de mantenimiento de una planta"></label></div>' +
      '<label class="fld"><span>Objetivo (qué tema de la clase van a ver)</span><input id="in-obj" placeholder="Ej. ver cilindros y válvulas funcionando (3er parcial)"></label>' + btn('Agregar', 'in-add', '', 'primary'));
    its.forEach(it => {
      const T = TIPOS[it.tipo] || TIPOS.charla, ck = it.ck || {}, n = T[1].filter((x, i) => ck[i]).length;
      h += card('<div class="row between gap wrap"><h3>' + T[0] + (it.q ? ': ' + esc(it.q) : '') + '</h3><span class="chip ' + (n === T[1].length ? 'ok' : it.fecha && it.fecha < hoy ? 'bad' : 'warn') + '">' + n + ' de ' + T[1].length + '</span></div>' +
        '<p class="small">' + (it.fecha ? '<b>' + u.cap(u.fLarga(it.fecha)) + '</b>' + (it.fecha >= hoy ? ' · faltan ' + u.diffDays(hoy, it.fecha) + ' días' : ' · ya pasó') : 'Sin fecha') + (it.obj ? ' · ' + esc(it.obj) : '') + '</p>' +
        '<ul class="in-ck">' + T[1].map((x, i) => '<li><label><input type="checkbox" data-ch="in-ck" data-id="' + it.id + '" data-i="' + i + '" ' + (ck[i] ? 'checked' : '') + '> ' + esc(x) + '</label></li>').join('') + '</ul>' +
        '<label class="fld"><span>Notas</span><input data-ch="in-nota" data-id="' + it.id + '" value="' + esc(it.nota || '') + '" placeholder="Acuerdos, hora, qué llevar"></label>' +
        '<div class="row gap wrap mt">' + (it.tipo === 'visita' ? btn('🖨 Autorización para padres', 'in-perm', 'data-id="' + it.id + '"', 'small') : '') + btn('📽 Preguntas para el invitado', 'in-preg', '', 'small') + btn('Borrar', 'in-del', 'data-id="' + it.id + '"', 'small ghost danger') + '</div>');
    });
    h += card('<h3>💡 Ideas para vincular al grupo con la industria</h3><ul class="in-list">' + IDEAS.map(x => '<li><b>' + esc(x[0]) + ':</b> ' + esc(x[1]) + '</li>').join('') + '</ul>');
    h += card('<details data-sec="in-preg"><summary><b>Preguntas para el invitado</b> (los alumnos eligen 3 y las preparan)</summary><ol class="small">' + PREG.map(q => '<li>' + esc(q) + '</li>').join('') + '</ol>' + btn('📽 Proyectar', 'in-preg', '', 'small') + '</details>');
    h += '<p class="muted small">Ejemplos regionales: armadoras y regiones de Guanajuato según mexicoindustry.com (ago 2026) y producción de 2025 según Mexico Business News; calzado de León y sombreros de San Francisco del Rincón. Para visitas con menores, sigue el protocolo y los formatos de tu plantel.</p>';
    return { t: 'Industria', h: h };
  };
  const upd = fn => { const g = D.grupoActual(); S.update(KV(g), d => { d.items = d.items || []; fn(d); }, { items: [] }); };
  const val = id => ((document.getElementById(id) || {}).value || '').trim();
  A['in-add'] = () => { const q = val('in-q'); if (!q) { u.toast('Escribe la empresa, el lugar o el invitado', 'err'); return; } upd(d => { d.items.push({ id: u.uid('vi'), tipo: val('in-tipo') || 'visita', fecha: val('in-f'), q: q, obj: val('in-obj'), ck: {} }); }); u.toast('Agregado con su lista de pendientes', 'ok'); };
  CH['in-ck'] = el => upd(d => { const it = d.items.find(x => x.id === el.dataset.id); if (it) { it.ck = it.ck || {}; it.ck[el.dataset.i] = el.checked; } });
  CH['in-nota'] = el => upd(d => { const it = d.items.find(x => x.id === el.dataset.id); if (it) it.nota = el.value.trim(); });
  A['in-del'] = el => { if (!confirm('¿Borrar esta actividad?')) return; upd(d => { d.items = d.items.filter(x => x.id !== el.dataset.id); }); };
  A['in-preg'] = () => E.proj.abrir({ id: 'preguntas-invitado', titulo: 'Preguntas para el invitado' }, [{ k: 'cover', h: 'Preguntas para nuestro invitado', sub: 'Conexión con la industria', p: 'Elige 3, escríbelas en tu libreta y prepárate para preguntar.' }, { k: 'list', h: 'Preguntas (1)', items: PREG.slice(0, 5) }, { k: 'list', h: 'Preguntas (2)', items: PREG.slice(5) }]);
  A['in-perm'] = el => {
    const g = D.grupoActual(), it = (doc(g).items || []).find(x => x.id === el.dataset.id), c = D.cfg(); if (!it) return;
    const una = '<div class="pr in-perm"><div class="p-title">AUTORIZACIÓN PARA VISITA ESCOLAR</div><p class="tiny c">' + esc(c.plantel || '') + ' · ' + esc(g.carrera || '') + ' · Grupo ' + esc(g.nombre) + '</p>' +
      '<p>Lugar de la visita: <b>' + esc(it.q) + '</b></p><p>Fecha: <b>' + (it.fecha ? u.fFecha(it.fecha) : '____________________') + '</b> · Hora de salida: ________ · Hora aproximada de regreso: ________</p>' +
      '<p>Objetivo: ' + (it.obj ? esc(it.obj) : '__________________________________________________________') + '</p><p>Transporte: _____________________________ · Docente responsable: ' + esc(c.docente || '') + '</p>' +
      '<p>Yo, ____________________________________________, madre, padre o tutor(a) de ____________________________________________, autorizo que participe en esta visita escolar y me comprometo a que respete las reglas de seguridad del lugar.</p>' +
      '<p>Teléfono de emergencia: ______________________ &nbsp; Firma: ______________________________</p></div>';
    E.print.run(una + '<div class="in-corte"></div>' + una, { title: 'Autorización visita ' + it.q, margin: '10mm' });
  };
})();
